name: nyc_taxi_engineering
description: Load and transform the raw NYC taxi data from four different files into
  a combined table
version: 0.0.1
author: matthew+public_demo@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: nyctaxiengineering
  parentArtefactID: matthewpublicdemoprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-26 09:37:26'
pipelines:
  pipelines/zones_load:
    name: zones_load
    description: ''
    author: matthew+public_demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-26 15:03:19'
    datasets:
      inputs:
      - datasets/zones_load
      outputs:
      - datasets/zones
    subgraphs: []
    dependencies: {}
  pipelines/green_taxi_raw:
    name: green_taxi_raw
    description: ''
    author: matthew+public_demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-28 14:57:41'
    datasets:
      inputs:
      - datasets/green_taxi_raw
      outputs:
      - datasets/combined_taxi_data
    subgraphs: []
    dependencies: {}
  pipelines/weather_data:
    name: weather_data
    description: ''
    author: matthew+public_demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-28 15:05:40'
    datasets:
      inputs: []
      outputs:
      - datasets/weather_precipitation_sum_dbx
    subgraphs: []
    dependencies: {}
  pipelines/yellow_taxi_raw:
    name: yellow_taxi_raw
    description: ''
    author: matthew+public_demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-28 15:35:13'
    datasets:
      inputs:
      - datasets/yellow_taxi_raw
      outputs:
      - datasets/combined_taxi_data
    subgraphs: []
    dependencies: {}
  pipelines/pull_files_from_url_dbx:
    name: pull_files_from_url_dbx
    description: ''
    author: matthew+public_demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-09 08:31:22'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/weather_data_options:
    name: weather_data_options
    description: ''
    author: matthew+public_demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-14 13:36:02'
    datasets:
      inputs:
      - datasets/weather_data_source
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/zones_load:
    name: zones_load
    description: ''
    author: matthew+public_demo@prophecy.io
    createdAt: '2024-03-26 15:14:48'
    mode: batch
    physicalDatasets:
      databricks-demo:
        fabricId: 10584
        datasetType: File
        description: ''
        author: matthew+public_demo@prophecy.io
        createdAt: '2024-03-26 15:14:48'
  datasets/zones:
    name: zones
    description: ''
    author: matthew+public_demo@prophecy.io
    createdAt: '2024-03-26 15:15:46'
    mode: batch
    physicalDatasets:
      databricks-demo:
        fabricId: 10584
        datasetType: Database
        description: ''
        author: matthew+public_demo@prophecy.io
        createdAt: '2024-03-26 15:15:46'
  datasets/green_taxi_raw:
    name: green_taxi_raw
    description: ''
    author: matthew+public_demo@prophecy.io
    createdAt: '2024-03-28 14:59:06'
    mode: batch
    physicalDatasets:
      databricks-demo:
        fabricId: 10584
        datasetType: File
        description: ''
        author: matthew+public_demo@prophecy.io
        createdAt: '2024-03-28 14:59:06'
  datasets/weather_data_source:
    name: weather_data_source
    description: ''
    author: matthew+public_demo@prophecy.io
    createdAt: '2024-03-28 15:08:38'
    mode: batch
    physicalDatasets:
      databricks-demo:
        fabricId: 10584
        datasetType: WebApp
        description: ''
        author: matthew+public_demo@prophecy.io
        createdAt: '2024-03-28 15:08:38'
  datasets/yellow_taxi_raw:
    name: yellow_taxi_raw
    description: ''
    author: matthew+public_demo@prophecy.io
    createdAt: '2024-03-28 15:39:50'
    mode: batch
    physicalDatasets:
      databricks-demo:
        fabricId: 10584
        datasetType: File
        description: ''
        author: matthew+public_demo@prophecy.io
        createdAt: '2024-03-28 15:39:50'
  datasets/combined_taxi_data:
    name: combined_taxi_data
    description: ''
    author: matthew+public_demo@prophecy.io
    createdAt: '2024-03-28 15:46:09'
    mode: batch
    physicalDatasets:
      databricks-demo:
        fabricId: 10584
        datasetType: Database
        description: ''
        author: matthew+public_demo@prophecy.io
        createdAt: '2024-03-28 15:46:09'
  datasets/weather_precipitation_sum_dbx:
    name: weather_precipitation_sum_dbx
    description: ''
    author: matthew+public_demo@prophecy.io
    createdAt: '2024-05-07 08:20:42'
    mode: batch
    physicalDatasets:
      databricks-demo:
        fabricId: 10584
        datasetType: Database
        description: ''
        author: matthew+public_demo@prophecy.io
        createdAt: '2024-05-07 08:20:42'
  datasets/taxi_data_iterator_source:
    name: taxi_data_iterator_source
    description: ''
    author: matthew+public_demo@prophecy.io
    createdAt: '2024-05-31 12:05:13'
    mode: batch
    physicalDatasets:
      databricks-demo:
        fabricId: 10584
        datasetType: Database
        description: ''
        author: matthew+public_demo@prophecy.io
        createdAt: '2024-05-31 12:05:13'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/WeatherDataGet:
      name: WeatherDataGet
      category: Custom
      subCategory: ''
      description: null
      author: matthew+public_demo@prophecy.io
      mode: batch
      files:
      - matthewpublicdemoprophecyioteam_nyctaxiengineering/gems/weather_api_get.py
      gemType: ComponentGem
      dependencies: []
      createdAt: '2024-04-30 15:31:12'
    gems/FileURLDownload:
      name: FileURLDownload
      category: Custom
      subCategory: ''
      description: null
      author: matthew+public_demo@prophecy.io
      mode: batch
      files:
      - matthewpublicdemoprophecyioteam_nyctaxiengineering/gems/FileURLDownload.py
      gemType: ComponentGem
      dependencies: null
      createdAt: '2024-05-01 15:05:18'
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-26 09:37:26'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-05-31T12:01:58.309607Z'
  name: plibMaven
  version: 8.0.11
  id: '235665184'
  createdAt: '2024-05-31T12:01:58.309481Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2024-05-31T12:01:58.30969Z'
  name: plibPypi
  version: 1.9.5
  id: '611966800'
  createdAt: '2024-05-31T12:01:58.309662Z'
  enabled: true
  entity: Project
- type: pypi
  modifiedAt: '2024-03-26T10:22:13.143Z'
  package: databricks-mosaic
  name: databricks-mosaic
  description: Databricks mosaic library for geospatial work
  enabled: true
  id: 6YCo44jDfNttBggN_Nvic
  createdAt: '2024-03-26T09:39:40.826Z'
  entity: Project
  editable: true
- type: pypi
  modifiedAt: '2024-03-28T15:06:16.585Z'
  package: prophecy_spark_ai
  name: prophecy_spark_ai
  description: ''
  enabled: true
  id: I8XSHogYejqnvjqs09bDK
  createdAt: '2024-03-28T15:06:16.585Z'
  entity: Project
  editable: true
- type: pypi
  modifiedAt: '2024-05-02T07:20:36.255Z'
  package: google-cloud-storage
  name: google-cloud-storage
  description: ''
  enabled: true
  id: qt3B7BvpBPLw5L58Ucgu-
  createdAt: '2024-05-02T07:20:36.255Z'
  entity: Project
  editable: true
- type: pypi
  modifiedAt: '2024-05-02T07:28:50.704Z'
  package: oauth2-client
  name: oauth2-client
  description: ''
  enabled: true
  id: x6_n9qNAsWZzqINrvQEsn
  createdAt: '2024-05-02T07:28:50.704Z'
  entity: Project
  editable: true
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-06-19 16:43:06'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-06-19 16:43:02'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
